# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 480
    - 360
    - 32

  fea_dim: 9
  out_fea_dim: 256
  num_class: 10
  num_input_features: 32 #16
  use_norm: True
  # init size should be 48 for the x1.5 model, 32 otherwise
  init_size: 32 #32 #16


###################
## Dataset options
dataset_params:
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "SemKITTI_sk"
  ignore_label: 0
  return_test: True
  fixed_volume_space: True
  label_mapping: "./config/label_mapping/kittipanda_ground.yaml"
  max_volume_space:
    - 50
    - 3.1415926
    - 2.27
  min_volume_space:
    - 0
    - -3.1415926
    - -3.73

###################
## Data_loader options
train_data_loader:
  data_path: "/media/map4/SSD_62/SemanticKitti/kittipanda_ms20_v005/sequences"
  imageset: "train"
  return_ref: True
  batch_size: 2
  shuffle: True
  num_workers: 4

val_data_loader:
  data_path: "/media/map4/SSD_62/SemanticKitti/kittipanda_ms20_v005/sequences"
  imageset: "val"
  return_ref: True
  batch_size: 1
  shuffle: False
  num_workers: 0 #4


###################
## Train params
train_params:
  model_load_path: ""
  model_save_path: "./model_save_dir/road_segmentation3/model"
  checkpoint_every_n_steps: 5000
  max_num_epochs: 20 #40
  eval_every_n_steps: 15001
  learning_rate: 0.002 #1
